/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container": "#efefd9",
        "inverse-primary": "#b8d300",
        "on-secondary-fixed-variant": "#454749",
        "surface-variant": "#e3e4ce",
        "surface-container-highest": "#e3e4ce",
        "on-background": "#1b1d10",
        "tertiary-fixed": "#c8e8f1",
        "secondary-container": "#e2e2e5",
        "surface": "#fafbe5",
        "surface-tint": "#576500",
        "on-primary-fixed": "#191e00",
        "surface-container-low": "#f5f5df",
        "on-primary-fixed-variant": "#414c00",
        "surface-container-high": "#e9ead4",
        "secondary-fixed": "#e2e2e5",
        "on-surface-variant": "#454932",
        "surface-dim": "#dbdbc6",
        "outline-variant": "#c6c9ab",
        "on-secondary-container": "#636467",
        "on-tertiary-fixed-variant": "#2e4b52",
        "primary-fixed-dim": "#b8d300",
        "on-secondary-fixed": "#1a1c1e",
        "on-tertiary-fixed": "#001f26",
        "on-tertiary-container": "#547279",
        "on-surface": "#1b1d10",
        "primary-container": "#dfff00",
        "surface-bright": "#fafbe5",
        "on-primary": "#ffffff",
        "primary": "#576500",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2f2dc",
        "on-error-container": "#93000a",
        "secondary": "#5d5e61",
        "inverse-surface": "#303223",
        "error-container": "#ffdad6",
        "background": "#fafbe5",
        "primary-fixed": "#d2f000",
        "tertiary-fixed-dim": "#acccd4",
        "tertiary": "#45636b",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#647400",
        "outline": "#767960",
        "secondary-fixed-dim": "#c6c6c9",
        "tertiary-container": "#d6f6ff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "brand-surface": "#F4F6FB",
        "brand-card": "#EEF2FA",
        "brand-border": "#D9DFEA",
        "brand-dark": "#1A1C1E"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "card": "18px",
        "input": "12px"
      },
      "spacing": {
        "gutter": "24px",
        "margin-desktop": "64px",
        "section-desktop": "120px",
        "section-gap": "120px",
        "section-tablet": "80px",
        "container-max": "1440px",
        "base": "8px",
        "section-mobile": "48px"
      },
      maxWidth: {
        "container-max": "1440px",
      },
      "fontFamily": {
        "sans": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "display-xl": ["Space Grotesk", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "display-lg": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "display-xl": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
